name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: fp-sisop
  REGION: asia-southeast2
  GAR_LOCATION: asia-southeast2-docker.pkg.dev/fp-sisop/itsparking/itsparking:latest

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Use gcloud CLI
        run: gcloud info